version: '3'
services:
  tagger:
    build: 
      context: ./
      dockerfile: Dockerfile
      # Useful during development
      #volumes:
      #- /home/apohllo/src/nlp/3rd-party/krnnt:/home/krnnt/krnnt
    command: bash -c "cd /home/krnnt/krnnt/ && ./start_gunicorn_server.sh"
    tty: true
    stdin_open: true
    ports:
      - "9200:9200"
    environment:
      WORKERS: 1
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
